# =============================
# Basic Site Settings
# =============================
locale        : "en-US"
site_theme    : "default"
title         : "Rachel Gui — Academic Website"
title_separator: "-"
name          : &name "Rachel Gui"
description   : &description "HCI • Physiological sensing • Wearables"
url           : "https://rachel-gui.github.io"   # your site base URL (no trailing slash)
baseurl       : "/Rachel_Gui"                    # if this is a project site; set "" if repo is rachel-gui.github.io
repository    : "Rachel-Gui/Rachel_Gui"

# =============================
# Author (shown in sidebar/profile)
# =============================
author:
  # IDs
  github          : "Rachel-Gui"

  # Bio
  avatar          : "profile.png"      # put your image in /images/ and change to "images/profile.png" if needed
  name            : "Rachel Gui"
  pronouns        : "she/her"
  bio             : "HCI researcher working on physiological sensing, IMU/PPG wearables, and human–AI interaction."
  location        : "Seattle, WA"
  employer        : "University of Washington"
  uri             :
  email           : "ruichen_gui@outlook.com"

  # Academic profiles (fill in as you create/claim them)
  googlescholar   : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  orcid           : ""   # e.g., "https://orcid.org/0000-0000-0000-0000"
  researchgate    :
  pubmed          :
  scopus          :
  arxiv           :
  academia        :
  semantic        :

  # Dev/design profiles (optional)
  kaggle          :
  stackoverflow   :

  # Social (fill the ones you use)
  linkedin        : ""   # e.g., "in/your-id"
  twitter         : ""   # X handle without @
  bluesky         : ""   # e.g., "yourname.bsky.social"
  instagram       :
  youtube         : ""   # channel/user handle
  bilibili        : ""   # if you plan to embed from Bilibili, keep here for reference
  mastodon        :
  medium          :
  zhihu           :

# =============================
# Publication Categories
# =============================
publication_category:
  books:
    title: "Books"
  manuscripts:
    title: "Journal Articles"
  conferences:
    title: "Conference Papers"

# =============================
# Site Settings
# =============================
teaser            :
breadcrumbs       : false
words_per_minute  : 160
future            : true
read_more         : "disabled"
talkmap_link      : false

comments:
  provider        : false

atom_feed:
  hide            : false
  path            :

# =============================
# SEO
# =============================
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing defaults
twitter:
  username        :
facebook:
  username        :
  app_id          :
  publisher       :
og_image          :
og_description    :

social:
  type            : Person
  name            : "Rachel Gui"
  links           : []

# =============================
# Analytics
# =============================
analytics:
  provider        : "false"
  google:
    tracking_id   :

# =============================
# Reading Files
# =============================
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding       : "utf-8"
markdown_ext   : "markdown,mkdown,mkdn,mkd,md"

# =============================
# Conversion
# =============================
markdown       : kramdown
highlighter    : rouge
lsi            : false
excerpt_separator: "\n\n"
incremental    : false

# =============================
# Markdown Processing
# =============================
kramdown:
  input         : GFM
  hard_wrap     : false
  auto_ids      : true
  footnote_nr   : 1
  entity_output : as_char
  toc_levels    : 1..6
  smart_quotes  : lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# =============================
# Collections
# =============================
collections:
  teaching:
    output   : true
    permalink: /:collection/:path/
  publications:
    output   : true
    permalink: /:collection/:path/
  portfolio:
    output   : true
    permalink: /:collection/:path/
  talks:
    output   : true
    permalink: /:collection/:path/

# =============================
# Defaults
# =============================
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout        : single
      author_profile: true
      read_time     : true
      comments      : false
      share         : true
      related       : true

  - scope:
      path: ""
      type: pages
    values:
      layout        : single
      author_profile: true

  - scope:
      path: ""
      type: teaching
    values:
      layout        : single
      author_profile: true
      share         : true
      comments      : false

  - scope:
      path: ""
      type: publications
    values:
      layout        : single
      author_profile: true
      share         : true
      comments      : false

  - scope:
      path: ""
      type: portfolio
    values:
      layout        : single
      author_profile: true
      share         : true
      comments      : false

  - scope:
      path: ""
      type: talks
    values:
      layout        : talk
      author_profile: true
      share         : true

# =============================
# Sass/SCSS
# =============================
sass:
  sass_dir: _sass
  style   : compressed

# =============================
# Outputting
# =============================
permalink : /:categories/:title/
timezone  : America/Los_Angeles

# =============================
# Plugins
# =============================
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# =============================
# Archives
# =============================
category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

# =============================
# HTML Compression
# =============================
compress_html:
  clippings: all
  ignore:
    envs: development
